services:
  app:
    build: .
    container_name: warehouse_app
    restart: always
    networks:
      - main
    expose:
      - 8000
    volumes:
      - static_volume:/code/static
      - media_volume:/code/media
    depends_on:
      - redis

  nginx:
    build: nginx/
    container_name: warehouse_nginx
    restart: always
    networks:
      - main
    ports:
      - 80:80
    volumes:
      - static_volume:/code/static
      - media_volume:/code/media

  database:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    networks:
      - main
    ports:
      - 5432:5432
    env_file: ./app/warehouse/.env
    volumes:
      - pgdata:/var/lib/postgresql/data/

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    networks:
      - main
    ports:
      - 6379:6379

  celery:
    build: .
    container_name: celery_warehouse
    command: celery -A warehouse worker -l INFO
    restart: always
    networks:
      - main
    depends_on:
      - app
      - redis
      - database

volumes:
  pgdata:
  static_volume:
  media_volume:

networks:
  main:
